model:
  name: 'efficientnet'
  params:
    model_name: 'efficientnet-b0'
    in_channels: 3
    num_classes: 5

dataset:
  name: 'CassavaDataset'
  train_csv: './input/cassava-leaf-disease-classification/train.csv'
  image_dir: './input/cassava-leaf-disease-classification/train_images_224x224'

train:
  folds: 5
  epochs: 100
  batch_size: 64

test:
  batch_size: 64
