data:
  name: 'MelanomaDataset'
  dir: './input/384x384/'

model:
  name: 'efficientnet'
  params:
    model_name: 'efficientnet-b2'
    num_classes: 1
    in_channels: 3
    num_metas: 2

train:
  out_dir: './output/eff2_384x384_5fold/'
  batch_size: 32
  num_epochs: 10
  num_folds: 5

valid:
  batch_size: 32

test:
  batch_size: 32

