data:
  name: 'MelanomaDataset'
  dir: './input/192x192/'

model:
  name: 'efficientnet'
  params:
    model_name: 'efficientnet-b3'
    num_classes: 1
    in_channels: 3
    num_metas: 2

train:
  out_dir: './output/eff3_192x192_5fold/'
  batch_size: 88
  num_epochs: 10
  num_folds: 5

valid:
  batch_size: 88

test:
  batch_size: 88

