data:
  name: 'MelanomaDataset'
  dir: './input/128x128/'

model:
  name: 'efficientnet'
  params:
    model_name: 'efficientnet-b0'
    num_classes: 1
    in_channels: 3
    num_metas: 2

train:
  out_dir: './output/test/'
  batch_size: 256
  num_epochs: 2
  num_folds: 5

valid:
  batch_size: 256

test:
  batch_size: 256

