model:
  name: 'efficientnet'
  params:
    model_name: 'efficientnet-b0'
    in_channels: 3
    num_classes: 1

dataset:
  name: 'CassavaDataset'
  train_csv: './input/cassava-leaf-disease-classification/train.csv'
  image_dir: './input/cassava-leaf-disease-classification/train_images_800x600'
  width: 512
  height: 512

train:
  folds: 5
  epochs: 100
  batch_size: 24

test:
  batch_size: 24
